const os = require('os')
console.log('Arch',os.arch())
console.log('Free memo',os.freemem())
console.log('Drictory ',os.homedir())
console.log('Hostname ',os.hostname())
console.log('Platform ',os.platform())
console.log('Realeas ',os.release())